Add `rectangle` progress style
sindresorhus/DockProgress pull request #12
Opened 2020-10-08 10:55 UTC by tosbaha

I saw your [issue](https://github.com/sindresorhus/DockProgress/issues/11) and tried to add rounded rectangle style. Best regards.

2020-10-09 12:41 UTC, sindresorhus requested changes

2020-10-09 12:41 UTC, sindresorhus commented on Sources/DockProgress/DockProgress.swift
> +		case rectangle(width: Double, height: Double, x: Double, y: Double, color: NSColor = .controlAccentColorPolyfill)
Let's call it `squircle`, as that's what it's supposed to be.

I think it's enough with just a `radius` parameter here too, and default to the standard macOS 11 radius for icons. 

https://developer.apple.com/design/resources/

2020-10-09 12:41 UTC, sindresorhus commented on Sources/DockProgress/DockProgress.swift
> +		progressCircle.cornerRadius = 3
The corner radius should be based on the size. The ratio is 1:6.4.

Also use `.cornerCurve` too.

2020-10-09 12:41 UTC, sindresorhus commented on Sources/DockProgress/util.swift
> +		position = CGPoint.zero
```suggestion
		position = .zero
```

2020-10-09 12:41 UTC, sindresorhus commented on Sources/DockProgress/util.swift
> +		let cgPath = NSBezierPath(roundedRect: NSRect(x: x, y: y, width: width, height: height), cornerRadius: 3).reversed.cgPath
You should not hard-code the corner radius here.

2020-10-09 12:41 UTC, sindresorhus commented on Example/AppDelegate.swift
> +			.rectangle(width: 113, height: 113, x: 10, y: 10, color: .systemGreen),
Put it above circle everywhere as `circle` is not very useful anymore with macOS 11.

2020-10-09 12:41 UTC, sindresorhus commented
Thanks for working on this 🙌🏻

2020-10-30 10:34 UTC, tosbaha commented
Since you didn't answer my comments, I guess this issue is abondended. I am closing the issue.

2020-10-30 10:34 UTC, closed without merging

2020-10-31 00:57 UTC, sindresorhus commented
@tosbaha I'm confused. You're the one that didn't answer my comments. For example: https://github.com/sindresorhus/DockProgress/pull/12#discussion_r502396350

2020-10-31 08:07 UTC, tosbaha commented
I wrote a comment to each and every one. I don't know why it didn't show up on your page. It is my first time resolving an issue. Did I have to press a button? Here is what I see on my page.

<img width="812" alt="Screen Shot 2020-10-31 at 11 05 19" src="https://user-images.githubusercontent.com/971530/97774479-2919ba00-1b69-11eb-9ae6-e7c905065538.png">

2020-10-31 09:42 UTC, sindresorhus commented
You forgot to finalize the review. Notice the "Pending" badge.

2020-10-31 09:43 UTC, sindresorhus commented
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request#submitting-your-review

2020-10-31 12:43 UTC, tosbaha reviewed
I guess it is now showing up on your side too. I already deleted the repo and my changes. I thought you weren't interested. Sorry about that. I hope it helps you to get started somehow.

PS: Your main comment about the code was related to the usage of x,y, width, height data. However, if you try to use my code by making assumptions, it breaks lots of icons. I tried on Paw, Sublime Text, Settings apps. They all needed some customizations related to rectangle.

2020-10-31 12:43 UTC, tosbaha commented on Sources/DockProgress/DockProgress.swift
> +		case rectangle(width: Double, height: Double, x: Double, y: Double, color: NSColor = .controlAccentColorPolyfill)
I will change the name. So, if the API just accepts radius, what will be the usage of this radius? Is it for `cornerRadius` that I hard coded as 3 ? I added width, height,x and y because otherwise, there will be no customization options, to size and to position the rectangle. We must again hard code values for size and x and y. Because if X and Y are set as zero, line at the bottom cuts out. If we use passed radius to calculate x,y,height, and width there would be lots of hard coded values. How should we proceed?

2020-10-31 12:43 UTC, tosbaha commented on Sources/DockProgress/DockProgress.swift
> +		progressCircle.cornerRadius = 3
Something like 
Do you mean something like below?

```swift
		if #available(OSX 10.15, *) {
			progressSquircle.cornerCurve = .continuous
		}

2020-10-31 12:43 UTC, tosbaha commented on Example/AppDelegate.swift
> +			.rectangle(width: 113, height: 113, x: 10, y: 10, color: .systemGreen),
I can fix one easily.

2020-10-31 12:43 UTC, tosbaha commented on Sources/DockProgress/util.swift
> +		position = CGPoint.zero
This will be fixed too.